"""Add Task InputEvent and task_node_links

Revision ID: 3a9510003910
Revises: 
Create Date: 2026-02-08 15:57:21.645509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a9510003910'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('input_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('integration_id', sa.Integer(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('processing_started_at', sa.DateTime(), nullable=True),
    sa.Column('processing_completed_at', sa.DateTime(), nullable=True),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('created_task_ids', sa.JSON(), nullable=True),
    sa.Column('created_node_ids', sa.JSON(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_input_events_external_id'), 'input_events', ['external_id'], unique=False)
    op.create_index(op.f('ix_input_events_id'), 'input_events', ['id'], unique=False)
    op.create_index(op.f('ix_input_events_integration_id'), 'input_events', ['integration_id'], unique=False)
    op.create_index(op.f('ix_input_events_organization_id'), 'input_events', ['organization_id'], unique=False)
    op.create_index(op.f('ix_input_events_source_type'), 'input_events', ['source_type'], unique=False)
    op.create_index(op.f('ix_input_events_status'), 'input_events', ['status'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('assignee_name', sa.String(length=255), nullable=True),
    sa.Column('assignee_email', sa.String(length=255), nullable=True),
    sa.Column('assignee_user_id', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('due_date_text', sa.String(length=100), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('extraction_confidence', sa.Integer(), nullable=True),
    sa.Column('canvas_id', sa.Integer(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assignee_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['canvas_id'], ['canvases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_canvas_id'), 'tasks', ['canvas_id'], unique=False)
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_index(op.f('ix_tasks_organization_id'), 'tasks', ['organization_id'], unique=False)
    op.create_index(op.f('ix_tasks_source'), 'tasks', ['source'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    op.create_table('task_node_links',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('link_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'node_id')
    )
    # Note: Removed alter_column operations - SQLite doesn't support ALTER COLUMN
    # The existing columns work fine as-is (INTEGER for Boolean, VARCHAR for Enum)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_node_links')
    op.drop_index(op.f('ix_tasks_user_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_source'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_organization_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_canvas_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_input_events_status'), table_name='input_events')
    op.drop_index(op.f('ix_input_events_source_type'), table_name='input_events')
    op.drop_index(op.f('ix_input_events_organization_id'), table_name='input_events')
    op.drop_index(op.f('ix_input_events_integration_id'), table_name='input_events')
    op.drop_index(op.f('ix_input_events_id'), table_name='input_events')
    op.drop_index(op.f('ix_input_events_external_id'), table_name='input_events')
    op.drop_table('input_events')
    # ### end Alembic commands ###
